#!/bin/bash
# Tier 0+1 pre-registered measurement protocol (plan Task 10), any scene.
#
#   scripts/run_tier1_arms.sh --dataset DIR   --out DIR [--seed-cloud PATH]
#                             [--depth-dir DIR] [--normal-dir DIR]
#                             [--arms A,B,..] [--floors A,B[,C]]
#                             [--steps N] [--budget N] [--max-resolution N] [--seed N]
#   scripts/run_tier1_arms.sh --blender DIR   --out DIR ...        (NeRF-synthetic)
#
# WHY THIS IS A COMMITTED SCRIPT AND NOT SHELL HISTORY. A first attempt at this protocol
# was launched from an agent turn and died with it at step 7,500 of 30,000, leaving nothing
# behind -- the protocol existed only in one process's argv. Launch it DETACHED. `setsid`
# does not exist on macOS; use Python's `start_new_session=True`, which is a real setsid(2).
#
# DO NOT EDIT THIS FILE WHILE IT IS RUNNING. bash reads a script lazily by byte offset and
# re-reads after each command, so inserting or removing lines mid-run shifts those offsets
# and can make it execute garbage.
#
# ORDERING IS LOAD-BEARING AND ENFORCED HERE, NOT BY OPERATOR DISCIPLINE. Floors are run,
# scored, and WRITTEN before any treatment arm is scored. Checkpoint D verifies this by file
# mtime, so the phases must not be reordered or parallelised. Never run two scenes at once
# either: GPU contention corrupts every ms/step column.
#
# TWO RULES FOR ANY MUTATION TEST RUN AGAINST THIS WORK, both learned expensively. This
# project has now produced SIX test results that looked like evidence and were not: a
# fixture whose plane family made both rules agree; a test asserting over an empty array; an
# orientation test whose geometry put n_z at exactly 0; `**_ignored` swallowing `aux_colors`;
# a mutation battery run without `--with scikit-image`, where every "kill" was really an
# unrelated ModuleNotFoundError; and a monitor whose failure filter matched "oom" inside
# "playroom".
#
#   1. ASSERT ON THE FAILING TEST'S NAME, never on a failure count.
#   2. VERIFY THE MUTANT ACTUALLY CHANGES BEHAVIOUR -- one "killed" mutant had in fact
#      SURVIVED, having patched a cache's read side but not its write side.
#
# And the generalisation of both, from the flatten double-add: THREE INDEPENDENT
# MEASUREMENTS AGREEING IS ONLY EVIDENCE WHEN THEY CAN FAIL INDEPENDENTLY. The plan's probe,
# this fork's reproduction and the reviewer's all agreed on flatten's effect because all
# three ran the same doubled code.
#
# SCORING NOTES.
#   * thin-axis is scored against a reference cloud that was NEVER TRAINED ON. Scoring it
#     against the trained seed was an 11.6 deg error once, larger than every recipe gain in
#     CLAUDE.md's table. tier1_floors.py refuses to proceed if the arms disagree about the
#     reference or if it is the COLMAP points3D.txt the trainer seeded from.
#   * thin/thick RATIO is not thin-axis ANGLE. Different metrics; never substitute one.
#   * A scene with no masks reports mean coverage 100% and masked PSNR == unmasked PSNR.
#     Say so; do not let a "masked PSNR" column imply a masked result.
#   * ms/step is a SCHEDULE AVERAGE, not a full-resolution figure: --num-downscales
#     defaults to 2, so a 30k run spends a third of its steps at 1/16 of the pixels, a
#     third at 1/4, and a third at full -- mean 0.4375. Identical across arms, so A/Bs are
#     valid, but the number is not "at <max-resolution>".
set -euo pipefail

DATASET=""; BLENDER=""; OUT=""; SEED_CLOUD=""; DEPTH_DIR=""; NORMAL_DIR=""
STEPS=30000; BUDGET=500000; MAXRES=1920; SEED=42
ARMS="B0a,B0b,B0c,F1,R1"; FLOORS="B0a,B0b,B0c"
MG="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SPLATSTATS="$(cd "$MG/../../analyze/splatstats" 2>/dev/null && pwd || echo "")"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dataset) DATASET="$2"; shift 2;;
    --blender) BLENDER="$2"; shift 2;;
    --out) OUT="$2"; shift 2;;
    --seed-cloud) SEED_CLOUD="$2"; shift 2;;
    --depth-dir) DEPTH_DIR="$2"; shift 2;;
    --normal-dir) NORMAL_DIR="$2"; shift 2;;
    --arms) ARMS="$2"; shift 2;;
    --floors) FLOORS="$2"; shift 2;;
    --steps) STEPS="$2"; shift 2;;
    --budget) BUDGET="$2"; shift 2;;
    --max-resolution) MAXRES="$2"; shift 2;;
    --seed) SEED="$2"; shift 2;;
    --splatstats) SPLATSTATS="$2"; shift 2;;
    *) echo "unknown argument: $1" >&2; exit 2;;
  esac
done
[[ -n "$OUT" ]] || { echo "need --out" >&2; exit 2; }
[[ -n "$DATASET" || -n "$BLENDER" ]] || { echo "need --dataset or --blender" >&2; exit 2; }
[[ -z "$DATASET" || -z "$BLENDER" ]] || { echo "--dataset and --blender are exclusive" >&2; exit 2; }
mkdir -p "$OUT"; OUT="$(cd "$OUT" && pwd)"
SEED2=$((SEED + 1))
IFS=',' read -r -a ARM_LIST <<< "$ARMS"
IFS=',' read -r -a FLOOR_LIST <<< "$FLOORS"
# The third floor arm is the SEED floor; the first two share a seed and give the REPEAT
# floor, which is the correct yardstick for the paired same-seed A/Bs this protocol runs.
SEEDFLOOR_ARM="${FLOOR_LIST[2]:-}"

if [[ -n "$DATASET" ]]; then
  DATASET="$(cd "$DATASET" && pwd)"
  source_flags=(--colmap "$DATASET/sparse/0" --images "$DATASET/images")
  [[ -n "$DEPTH_DIR" ]] && source_flags+=(--depth-dir "$DEPTH_DIR")
  [[ -n "$NORMAL_DIR" ]] && source_flags+=(--normal-dir "$NORMAL_DIR")
else
  BLENDER="$(cd "$BLENDER" && pwd)"
  source_flags=(--blender "$BLENDER")
fi
common=("${source_flags[@]}" --max-resolution "$MAXRES" --steps "$STEPS"
        --budget "$BUDGET" --eval-split-every 8 --eval-every 2500)

arm_flags() {                    # extra flags per arm NAME
  case "$1" in
    B0a|B0b|B0c|L0a|L0b|L0c) : ;;
    F1|L1)  echo "--flatten-loss-weight 1.0" ;;
    L2)     echo "--depth-normal-weight 0.05" ;;
    # R1 moves THREE weights at once, deliberately: the recipe is tested as a unit, as
    # CLAUDE.md's "Indoor haze" measurement did. Nobody may later call it one-variable.
    R1)     echo "--flatten-loss-weight 1.0 --depth-loss-weight 1.0 --normal-loss-weight 0.2 --depth-normal-weight 0.05" ;;
    # R1p: the recipe WITHOUT depth-normal consistency. That term was measured on
    # 2026-09-02 to diverge on its own -- lego arm L2 ran it alone, at weight 0.05, on a
    # scene with no priors at all, and lost 17.7 dB against a 0.108 dB repeat floor while
    # its own logged value climbed monotonically. Until --depth-source plane-aux lands, a
    # run with --depth-normal-weight > 0 in `center` mode is a known-broken configuration,
    # so this arm gives the first clean read on the depth and normal PRIORS in isolation.
    R1p)    echo "--flatten-loss-weight 1.0 --depth-loss-weight 1.0 --normal-loss-weight 0.2" ;;
    *) echo "unknown arm $1" >&2; return 1 ;;
  esac
}
arm_seed() { [[ "$1" == "$SEEDFLOOR_ARM" ]] && echo "$SEED2" || echo "$SEED"; }

run_arm() {
  local arm="$1" seed extra
  seed="$(arm_seed "$arm")"; extra="$(arm_flags "$arm")"
  if [[ -f "$OUT/$arm.json" ]]; then echo "[$(date +%T)] $arm: report exists, skipping"; return; fi
  echo "[$(date +%T)] $arm: training (seed $seed) ${extra:-<baseline>}"
  ( cd "$MG" && caffeinate -i uv run --frozen python -m metal_gauss.train \
      "${common[@]}" --seed "$seed" \
      --report "$OUT/$arm.json" --export "$OUT/$arm.ply" --eval-dump "$OUT/$arm.dump" \
      $extra ) > "$OUT/$arm.log" 2>&1
  echo "[$(date +%T)] $arm: trained"
}

score_arm() {
  local arm="$1"
  echo "[$(date +%T)] $arm: scoring"
  if [[ -n "$SEED_CLOUD" && ! -f "$OUT/$arm.stats.json" ]]; then
    ( cd "$SPLATSTATS" && caffeinate -i uv run --frozen python scripts/splat_stats.py \
        "$OUT/$arm.ply" --seed "$SEED_CLOUD" --json "$OUT/$arm.stats.json" --quiet ) \
        >> "$OUT/$arm.log" 2>&1
  elif [[ -z "$SEED_CLOUD" ]]; then
    # No reference cloud for this scene: on-seed and thin-axis are UNDEFINED, not zero.
    echo "[$(date +%T)] $arm: no --seed-cloud, skipping splatstats (geometry metrics undefined)"
  fi
  [[ -f "$OUT/$arm.dump/lpips.json" ]] || \
    ( cd "$MG" && caffeinate -i uv run scripts/lpips_eval.py "$OUT/$arm.dump" ) \
      >> "$OUT/$arm.log" 2>&1
  echo "[$(date +%T)] $arm: scored"
}

echo "=== PHASE 1: floor arms (${FLOOR_LIST[*]}) ==="
for a in "${FLOOR_LIST[@]}"; do run_arm "$a"; done

echo "=== PHASE 2: score floors, then WRITE floors.json (must predate any treatment) ==="
for a in "${FLOOR_LIST[@]}"; do score_arm "$a"; done
( cd "$MG" && uv run --frozen python scripts/tier1_floors.py "$OUT" "${FLOOR_LIST[@]}" ) \
  | tee -a "$OUT/floors.log"
[[ -f "$OUT/floors.json" ]] || { echo "floors.json missing; refusing to grade arms" >&2; exit 1; }
touch "$OUT/FLOORS_DONE"

echo "=== PHASE 3: treatment arms ==="
for a in "${ARM_LIST[@]}"; do
  [[ " ${FLOOR_LIST[*]} " == *" $a "* ]] || run_arm "$a"
done

echo "=== PHASE 4: score treatments ==="
for a in "${ARM_LIST[@]}"; do
  [[ " ${FLOOR_LIST[*]} " == *" $a "* ]] || score_arm "$a"
done
touch "$OUT/ALL_DONE"
echo "[$(date +%T)] protocol complete: $OUT"
